config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', as: 'rate'
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#show'

  resource :home, only: :show

  namespace :user do
    resources :languages do
      resources :flashcards, except: :index
    end

    resources :flashcards, only: [] do
      member do
        get :check_answer
      end
    end
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch :ban, :unban
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ApplicationRecord
  belongs_to :rater, class_name: 'User'
  belongs_to :rateable, polymorphic: true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :user
  belongs_to :language

  validates :front, presence: true, uniqueness: true
  validates :back, presence: true
  validates :user_id, :language_id, presence: true

  ratyrate_rateable 'stars'

  def the_same?(params)
    back.casecmp(params[:back]).zero?
  end
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user
  has_many :flashcards, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { maximum: 24 }
  validates :user_id, presence: true

  paginates_per 10

  def random_flashcard
    flashcards.all[rand(flashcards.all.size)]
  end
end

app/models/overall_average.rb
class OverallAverage < ApplicationRecord
  belongs_to :rateable, polymorphic: true
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :rater, class_name: 'User'
  belongs_to :rateable, polymorphic: true

  # attr_accessible :rate, :dimension

  paginates_per 10
end

app/models/rating_cache.rb
class RatingCache < ApplicationRecord
  belongs_to :cacheable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :languages
  has_many :flashcards

  validates :name, presence: true, uniqueness: true, length: { maximum: 24 }

  paginates_per 5

  ratyrate_rater

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :banned?

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  def banned?
    if current_user&.banned?
      sign_out current_user
      redirect_to root_path, alert: 'Your account has been banned!'
    end
  end

  def not_authorized
    redirect_to root_path, alert: 'Permission denied!'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController
  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate(params[:score].to_f, current_user, params[:dimension])

      render json: true
    else
      render json: false
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(User) && resource.banned?
      sign_out resource
      redirect_to root_path, alert: 'Your account has been banned!'
    else
      super
    end
  end
end

app/controllers/user/flashcards_controller.rb
class User::FlashcardsController < User::UserController
  before_action :language, except: :check_answer
  before_action :flashcard, only: [:show, :edit, :update, :destroy, :check_answer]

  def show
  end

  def new
    @flashcard = Flashcard.new
  end

  def edit
    authorize @flashcard
  end

  def create
    @flashcard = @language.flashcards.new(flashcard_params.merge(user_id: current_user.id))

    if @flashcard.save
      redirect_to [:user, @language, @flashcard]
    else
      render 'new'
    end
  end

  def update
    authorize @flashcard
    if @flashcard.update(flashcard_params)
      redirect_to [:user, @language, @flashcard]
    else
      render 'edit'
    end
  end

  def destroy
    authorize @flashcard

    @flashcard.destroy
    redirect_to [:user, @language]
  end

  def check_answer
    if @flashcard.the_same?(params)
      current_user.points += 1
      current_user.save!

      render :correct, layout: false
    else
      render :incorrect, layout: false
    end
  end

  private

  def flashcard_params
    params.require(:flashcard).permit(:front, :back)
  end

  def language
    @language = Language.find(params[:language_id])
  end

  def flashcard
    @flashcard = Flashcard.find(params[:id])
  end
end

app/controllers/user/languages_controller.rb
class User::LanguagesController < User::UserController
  before_action :language, only: [:show, :edit, :update, :destroy]

  def index
    @query = Language.ransack(params[:q])
    @languages = @query.result(distinct: true).page(params[:page])
  end

  def show
    @flashcards = @language.flashcards.where.not(id: nil).page(params[:page])
  end

  def new
    @language = Language.new
  end

  def edit
    authorize @language
  end

  def create
    @language = current_user.languages.new(language_params)

    authorize @language
    if @language.save
      redirect_to [:user, @language]
    else
      render 'new'
    end
  end

  def update
    authorize @language
    if @language.update(language_params)
      redirect_to [:user, @language]
    else
      render 'edit'
    end
  end

  def destroy
    authorize @language

    @language.destroy
    redirect_to user_languages_path
  end

  private

  def language_params
    params.require(:language).permit(:name)
  end

  def language
    @language = Language.find(params[:id])
  end
end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < User::UserController
  before_action :user, only: [:show, :edit, :update, :ban, :unban]

  def index
    @query = User.ransack(params[:q])
    @users = @query.result.page(params[:page]).order(points: :desc)
  end

  def show
    @rates = Rate.where(rater_id: @user.id).page(params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def ban
    @user.update_attributes!(banned: true)
    redirect_to @user
  end

  def unban
    @user.update_attributes!(banned: false)
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

  def user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/flashcards/_form.slim
= simple_form_for [:user, @language, @flashcard] do |f|
  = f.input :front
  = f.input :back
  = f.button :submit
  
= link_to 'Back', user_languages_path

app/views/user/flashcards/correct.js.erb
$("#points").html("<%= current_user.points %>");
$("#correct").html("Correct!");
$("#incorrect").html("");

$("#check_answer_form").html("");

app/views/user/flashcards/edit.slim
h1 Edit flashcard
= render 'form'

app/views/user/flashcards/incorrect.js.erb
$("#points").html("<%= current_user.points %>");
$("#incorrect").html("<%= @flashcard.back %>");

app/views/user/flashcards/new.slim
h1 New flashcard
= render 'form'

app/views/user/flashcards/show.slim
h2 Flashcard

- if policy(@flashcard).edit?
  = link_to 'Edit', edit_user_language_flashcard_path, class: 'btn btn-warning'
  =>
  
- if policy(@flashcard).destroy?
  = link_to 'Delete', user_language_flashcard_path(@language, @flashcard), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'

p
  strong
    | Front:
  =>
  = @flashcard.front

p
  strong
    | Back:
  =>
  = @flashcard.back

p
  strong
    | Author:
    =>
  = @flashcard.user.email

p
  strong
    | Stars:
    =>
    = rating_for @flashcard, 'stars'

= link_to 'Back', user_languages_path, class: 'btn btn-default'

app/views/user/languages/_form.slim
= simple_form_for [:user, @language] do |f|
  = f.input :name
  = f.button :submit

= link_to 'Back', user_languages_path

app/views/user/languages/edit.slim
h1 Edit language
= render 'form'

app/views/user/languages/index.slim
h2 Languages

br

- if policy(Language.new).create?
  = link_to 'New language', new_user_language_path(@language), class: 'btn btn-warning'
  br
  br

div class="form-group form-inline"
  = search_form_for [:user, @query] do |f|
    = f.search_field :name_cont, class: 'form-control'
    = f.button :search, class: 'form-control'

br
  
- @languages.each do |language|
  span
    = link_to language.name, user_language_path(language), class: 'btn btn-primary'
    =>

= paginate @languages

app/views/user/languages/new.slim
h1 New language
= render 'form'

app/views/user/languages/show.slim
h2
  = @language.name
  
strong
  | My points:
  =>
  
span id="points"
  = current_user.points

- flashcard = @language.random_flashcard

- if flashcard
  div class="form-group form-inline" id="check_answer_form"
    = form_tag(check_answer_user_flashcard_path(flashcard), method: 'get', remote: true)
      = flashcard.front
      =>
      = text_field_tag(:back, nil, class: 'form-control')
      = submit_tag("Enter", class: 'form-control')
- else
  p Add flashcards to start!
  
div id="correct"
=>
div id="incorrect"
=>

= link_to 'Next', user_language_path(@language), class: 'btn btn-primary'
=>

- if policy(@language).update?
  = link_to 'Edit', edit_user_language_path, class: 'btn btn-warning'
  =>
  
- if policy(@language).destroy?
  = link_to 'Delete', user_language_path(@language), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'
  =>

= link_to 'New flashcard', new_user_language_flashcard_path(@language), class: 'btn btn-primary'
=>
= link_to 'Back', user_languages_path, class: 'btn btn-default'

br

br

form
  input type="button" class="btn btn-default" id="switch" value="Show flashcards"
  
div id="list"
  - @flashcards.each do |flashcard|
    p
      strong
        = flashcard.front
        =>
      = flashcard.back
      =>
      = link_to 'Show', user_language_flashcard_path(@language, flashcard)
  
  = paginate @flashcards

javascript:
  $(document).ready(function() {
    $("#switch").click(function() {
      $("#list").toggle('slow');
    });
  });

app/views/users/edit.slim
div class="form-group form-inline"
  = simple_form_for @user, html: { multipart: true } do |f|
    = f.label :avatar
    br
    = f.file_field :avatar, class: 'form-control'
    = f.submit class: 'form-control'

= link_to 'Back', user_path(@user)

app/views/users/index.slim
h2 Top users

div class="form-group form-inline"
  = search_form_for @query do |f|
    = f.search_field :name_cont, class: 'form-control'
    = f.button :search, class: 'form-control'
  
- @users.each do |user|
  p
    - if user.email
      = gravatar_image_tag(user.email)
    - else
      = image_tag(user.avatar, class: 'avatar')
    =>
    = link_to user.name, user_path(user), class: 'btn btn-default'
    =>
    = user.points
    =>
    | points
      
= paginate @users

app/views/users/show.slim
h2
  = @user.name

- if @user.email
  = gravatar_image_tag(@user.email)
- else
  = image_tag(@user.avatar, class: 'avatar')

br

strong
  | Total points:
  =>

= @user.points

br

- if @rates.any?
  strong
    | My stars:
    
  ul
  - @rates.each do |rate|
    li 
      strong
        = rate.rateable.front
        =>
      = rate.stars
      
  = paginate @rates
  br

- if @user == current_user
  = link_to 'Edit profile', edit_user_registration_path(@user), class: 'btn btn-warning'
  =>
  = link_to 'Upload avatar', edit_user_path(@user), class: 'btn btn-warning'

- if current_user.admin? && !@user.admin?
  - if @user.banned
    = link_to 'Unban user', unban_user_path, method: :patch, class: 'btn btn-warning'
  - else
    = link_to 'Ban user', ban_user_path, method: :patch, class: 'btn btn-danger'
  
= link_to 'Back', user_languages_path, class: 'btn btn-default'